"""New migrate with the models and the env.py updated

Revision ID: 2e89870878cd
Revises: e9239174d29a
Create Date: 2025-04-25 17:32:39.806134

"""
from typing import Sequence, Union
from sqlmodel import SQLModel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e89870878cd'
down_revision: Union[str, None] = 'e9239174d29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Enum('ACTION', 'THRILLER', 'DRAMA', 'COMEDY', 'HORROR', 'WESTERN', name='genreenum'), nullable=False),
    sa.Column('showtime', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=True)
    op.create_table('userindb',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('full_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('session_time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userindb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('session')
    op.drop_table('userindb')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
