"""Finished movie adjusts and added room and price fields to Session

Revision ID: 563e1e71cb11
Revises: ac95d5e8ccc0
Create Date: 2025-04-29 18:19:48.248480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563e1e71cb11'
down_revision: Union[str, None] = 'ac95d5e8ccc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('slug', sa.String(), nullable=False))
    op.drop_index('ix_movie_title', table_name='movie')
    op.create_index(op.f('ix_movie_slug'), 'movie', ['slug'], unique=True)
    op.create_unique_constraint(None, 'movie', ['title'])
    op.add_column('session', sa.Column('room', sa.String(), nullable=False))
    op.add_column('session', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'price')
    op.drop_column('session', 'room')
    op.drop_constraint(None, 'movie', type_='unique')
    op.drop_index(op.f('ix_movie_slug'), table_name='movie')
    op.create_index('ix_movie_title', 'movie', ['title'], unique=True)
    op.drop_column('movie', 'slug')
    # ### end Alembic commands ###
