"""Models finished, inheritance used

Revision ID: 7d0bdb77ec09
Revises: 563e1e71cb11
Create Date: 2025-04-30 13:09:12.242611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0bdb77ec09'
down_revision: Union[str, None] = '563e1e71cb11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('is_canceled', sa.Boolean(), nullable=False))
    op.drop_column('movie', 'showtime')
    op.alter_column('session', 'session_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.add_column('movie', sa.Column('showtime', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('booking', 'is_canceled')
    # ### end Alembic commands ###
