"""Booking status field added

Revision ID: e4e6702e3175
Revises: abd873ba8096
Create Date: 2025-05-08 12:48:50.500152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e6702e3175'
down_revision: Union[str, None] = 'abd873ba8096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    booking_status_enum = sa.Enum(
        'PENDING', 'COMPLETED', 'CANCELED', 'PAYMENT_PENDING', 'EXPIRED', 'CHECKED_IN', 'NO_SHOW', 'REFUNDED',
    name='bookingstatus'
    )
    booking_status_enum.create(op.get_bind())
    op.add_column('booking', sa.Column('status', booking_status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'status')
    # ### end Alembic commands ###
