"""Rating added

Revision ID: f45c1087bfc5
Revises: e4e6702e3175
Create Date: 2025-05-09 17:18:46.427860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45c1087bfc5'
down_revision: Union[str, None] = 'e4e6702e3175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratingdb',
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('stars', sa.Enum('ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', name='stars'), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userindb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratingdb')
    # ### end Alembic commands ###
